language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby
  - ruby-head
  - ree

script: rake test

notifications:
  webhooks:
    - http://rcmp.programble.co.cc/irc.tenthbit.net/programming
    - http://rcmp.programble.co.cc/irc.freenode.net/sicuro
  
  email:
    on_success: change # default: change
    on_failure: change # default: always




# Allowed failures
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: jruby
    - rvm: ruby-head
    - rvm: ree

